# Generated by Django 5.2.9 on 2025-12-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_submissionmedia_file_and_processed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmedia',
            name='file',
            field=models.FileField(blank=True, help_text='업로드된 파일(로컬 또는 스토리지)', max_length=500, null=True, upload_to='submission_media/%Y/%m/%d/'),
        ),
    ]
