# Generated by Django 5.2.2 on 2025-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_submissionmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmedia',
            name='ai_verification_at',
            field=models.DateTimeField(blank=True, help_text='AI 검증 실행 시간', null=True),
        ),
        migrations.AddField(
            model_name='submissionmedia',
            name='ai_verification_score',
            field=models.FloatField(blank=True, help_text='AI 유사도 점수 (0.0~1.0), scene_photo와 selfie 비교 결과', null=True),
        ),
        migrations.AddField(
            model_name='submissionmedia',
            name='ai_verification_status',
            field=models.CharField(choices=[('pending', 'AI 검증 대기'), ('processing', 'AI 검증 중'), ('completed', 'AI 검증 완료'), ('failed', 'AI 검증 실패')], default='pending', help_text='AI 검증 상태', max_length=20),
        ),
    ]
