# Generated by Django 5.2.2 on 2025-12-09 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomItem',
            fields=[
                ('room_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='아이템 이름', max_length=100)),
                ('category', models.CharField(choices=[('background', '배경'), ('furniture', '가구'), ('accessory', '소품')], help_text='아이템 카테고리', max_length=20)),
                ('cost', models.IntegerField(help_text='필요한 포인트')),
                ('image', models.ImageField(help_text='아이템 이미지', upload_to='room_items/')),
                ('z_index', models.IntegerField(default=1, help_text='레이어 순서 (높을수록 앞에 표시)')),
                ('default_top', models.IntegerField(default=0, help_text='기본 위치 (top, px)')),
                ('default_left', models.IntegerField(default=0, help_text='기본 위치 (left, px)')),
                ('width', models.IntegerField(default=100, help_text='이미지 가로 크기 (px)')),
                ('height', models.IntegerField(default=100, help_text='이미지 세로 크기 (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_item',
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='userpet',
            name='pet_type',
            field=models.CharField(choices=[('cat', '고양이'), ('dog', '강아지'), ('tree', '그루트')], default='otter', max_length=20),
        ),
        migrations.CreateModel(
            name='UserRoomDecoration',
            fields=[
                ('decoration_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_top', models.IntegerField(default=0, help_text='배치된 위치 (top, px)')),
                ('position_left', models.IntegerField(default=0, help_text='배치된 위치 (left, px)')),
                ('is_displayed', models.BooleanField(default=True, help_text='마이룸에 표시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_item_id', models.ForeignKey(db_column='room_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_placements', to='growth.roomitem')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_decorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_room_decoration',
                'ordering': ['room_item_id__z_index', 'created_at'],
                'unique_together': {('user_id', 'room_item_id')},
            },
        ),
    ]
